version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb-data: {}
  grafana-data: {}

services:
  influxdb:
    image: influxdb:1.8.10
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influxdb-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    user: 'root'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./universal-dashboard.yaml:/etc/grafana/provisioning/dashboards/universal.yaml
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
