global:
  scrape_interval: 1s

scrape_configs:
  # optional: this makes the metrics available to us about Promethus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # tells Prometheus to scrape metrics from StatsD
  - job_name: 'test_metrics'
    static_configs:
      - targets: ['host.docker.internal:9102']
        labels: {'host': 'lp-testing-demo-stand'}
