{
 "title": "Universal k6 Load&Performance Testing Dashboard (client-side metrics)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "worker_instance",
    "query": {
     "query": "label_values({__name__=~\"k6_http_req_duration| k6_http_reqs| k6_http_req_failed\"}, instance)"
    }
   },
   {
    "name": "subscenario",
    "query": {
     "query": "label_values({__name__=~\"k6_Duration_Trend| k6_Success_Rate| k6_Requests_Counter\"}, subscenario)"
    }
   },
   { "name": "data_source", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General Metrics (aggregated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "k6_http_req_duration average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (quantile)(k6_http_req_duration{quantile=\"0.99\",instance=~\"${worker_instance}\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg by (quantile)(k6_http_req_duration{quantile=\"0.9\",instance=~\"${worker_instance}\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg by (quantile)(k6_http_req_duration{quantile=\"0.5\",instance=~\"${worker_instance}\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "RPS by http_reqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "k6_http_reqs{instance=~\"$worker_instance\"}",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "http_req_failed sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(k6_http_req_failed{instance=~\"$worker_instance\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "General Metrics (by worker)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "http_req_duration $worker_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "worker_instance",
   "targets": [
    {
     "expr": "sum by(instance,quantile)(k6_http_req_duration{quantile=\"0.99\",instance=~\"${worker_instance}\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum by(instance,quantile)(k6_http_req_duration{quantile=\"0.9\",instance=~\"$worker_instance\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum by(instance,quantile)(k6_http_req_duration{quantile=\"0.5\",instance=~\"$worker_instance\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "RPS by http_reqs $worker_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "repeat": "worker_instance",
   "targets": [
    {
     "expr": "sum by (instance)(k6_http_reqs{instance=~\"$worker_instance\"})",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "http_req_failed $worker_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "repeat": "worker_instance",
   "targets": [
    {
     "expr": "sum by(instance)(k6_http_req_failed{instance=~\"$worker_instance\"})",
     "legendFormat": "failed requests"
    }
   ]
  },
  {
   "title": "Specific Metrics (by subscenario)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Duration Trend $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "repeat": "subscenario",
   "targets": [
    {
     "expr": "avg by (subscenario,quantile)(k6_Duration_Trend{subscenario=~\"$subscenario\",quantile=\"0.5\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg by (subscenario,quantile)(k6_Duration_Trend{subscenario=~\"$subscenario\",quantile=\"0.9\"})",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg by (subscenario,quantile)(k6_Duration_Trend{subscenario=~\"$subscenario\",quantile=\"0.99\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "RPS by Requests Counter $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "repeat": "subscenario",
   "targets": [
    {
     "expr": "sum by (subscenario)(k6_Requests_Counter{subscenario=~\"$subscenario\"})",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Success Rate $subscenario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "repeat": "subscenario",
   "targets": [
    {
     "expr": "sum by (subscenario)(k6_Success_Rate{subscenario=~\"$subscenario\"})/sum by (subscenario)(k6_Requests_Counter{subscenario=~\"$subscenario\"})",
     "legendFormat": "success rate"
    }
   ]
  }
 ]
}